services:
  - type: web
    name: ledai
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: TZ
        value: Asia/Bangkok
      - key: TIKWM_API_BASE
        value: https://www.tikwm.com
      - key: YTDLP_PROXY
        sync: false
      - key: PROXYXOAY_KEY
        sync: false
      - key: PROXYXOAY_API_BASE
        value: https://proxyxoay.shop
      - key: PROXYXOAY_CACHE_MS
        value: "45000"
      - key: YTDLP_COOKIES_B64
        sync: false
      - key: SCRAPINGBEE_API_KEY
        sync: false
